# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Framework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_location',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_marker_data',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.CharField(max_length=20),
        ),
    ]
